site_name: {{ cookiecutter.project_name }}
site_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.github_repository }}
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.github_repository }}
edit_uri: "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.github_repository }}/edit/main/docs"

theme:
  name: material
  language: en
  features:
    - navigation.instant
  palette:
    primary: black
    accent: light blue

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: 🔗

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/{{ cookiecutter.linkedin }}
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/{{ cookiecutter.github_username }}
      name: GitHub
    - icon: fontawesome/solid/paper-plane
      link: mailto:{{ cookiecutter.email }}
      name: Email